### ISSUE TITLE
VM_Makefile

### ISSUE THREAD

**Issue by dalawwa** [dalawwa/Corewar#1]
Le makefile ne recompile pas après un changement des sources de corewar.

**Comment by dalawwa** [comment]
- Ne relink pas
- Recompile uniquement les dependences qui ont changé (libft est une dependence de corewar donc si on touch a atoi.c on recompile atoi, on refait la libft et on recompile corewar avec la nouvelle lib)

- Il vaut mieux garder la version verbeuse et un peu moche pour s'assurer que rien nous échappe pour l'instant (ou pour toujours :D).

**Comment by dalawwa** [comment]
Changer les flags de compilation. Ne garder que Wall Wextra Werror

**Comment by dalawwa** [comment]
- Faire en sorte que le Makefile affiche bien "Nothing to be done" 1 fois pour la libft et 1 autre fois pour celui de la VM

**Comment by benfruch** [comment]
To fix.
Checks all .o when not necessary.
