### ISSUE TITLE
Regarder comment la vm de zaz réagit avec des octets d'encodage invalides sur des instructions valides

### ISSUE THREAD

**Issue by dalawwa** [dalawwa/Corewar#20]

**Comment by vbaudron** [comment]
TEST Fait : Jai change l'OCP dans un .cor.
result quqnd tu lance corewar 

**Error: File ./test_cor_wrong_ocp/wrong.cor has an invalid header**

**Comment by dalawwa** [comment]
https://docs.google.com/spreadsheets/d/1DkEsrnVYLCcQrebpw_z-86ecX-geC8V5E3SctIVw59w/edit#gid=1051924689

**Comment by dalawwa** [comment]
Fixed
